import React from 'react';

const cards = [['Historical player stats', 'NBA team-season totals are converted to per-game values before optimization. A 15-player course demo and compatible CSV imports are also available.'], ['How to read results', 'The result summary keeps the statline, decision quality, and optional game points separate. Decision quality reports the eligible-group rank and search coverage—not a basketball performance metric.'], ['Exact constraints', 'Rotation mode ranks eligible combinations; five-player lineup mode may return a bounded set of groups. Locked and excluded players, position assignments, and minute limits are hard rules.'], ['Honest limitations', 'Box scores do not directly measure chemistry, matchups, role changes, or on-court possessions. Per-100 views are estimates. Recommended Historical scoring uses paired observed counts and same-season priors. Zero-attempt shooters receive no demonstrated spacing credit. Strong players may still reach your maximum; only your displayed minimum and maximum are hard caps. OBPM and DBPM are player-season box-score estimates, not five-player chemistry or lineup impact. Play-by-play impact estimates are shown separately when available.']];
export default function LineupModelGuide() {
  return <section id="modelView" className="ll-native-card" data-view="model" role="tabpanel" aria-labelledby="modelTab" tabIndex="-1" hidden>
    <p className="court-kicker">Transparent by design</p><h2>Data, scoring, and limitations</h2><p className="helper">The optimizer keeps its math visible and its historical data boundary explicit.</p>
    <div className="model-grid">{cards.map(([title, text], index) => <article key={title}><span className="ll-native-index">0{index + 1}</span><h3>{title}</h3><p>{text}</p>{index === 0 && <div className="card-actions"><button id="exportDatasetButton" type="button" className="text-button">Export current CSV</button><button id="downloadTemplateButton" type="button" className="text-button">Download CSV template</button></div>}</article>)}</div>
    <div className="ll-native-note mt-5"><h3>Historical data boundary</h3><p>The selected team-season pool shows players who appeared for that team. If a player changed teams, the displayed rates use that team's row, but games and minutes do not set their role. This is not a current depth chart, injury report, prediction, or betting service.</p></div>
  </section>;
}