import React, { useState } from 'react';
import { X } from 'lucide-react';
import TeamMark from '@/components/studio/TeamMark';
import PlayerPortrait from '@/components/players/PlayerPortrait';
import BlueprintStatGrid from '@/components/players/BlueprintStatGrid';
import BlueprintStatsTable from '@/components/players/BlueprintStatsTable';
import TrophyCase from '@/components/players/TrophyCase';
import PlayerBio from '@/components/players/PlayerBio';
import usePlayerContext from '@/components/players/usePlayerContext';
export default function BlueprintPlayerCard({ player, onRemove }) {
  const [tab,setTab] = useState('profile');
  const { context,status } = usePlayerContext(player.name);
  return <article className="court-panel overflow-hidden"><header className="relative border-b border-border/30 bg-canvas/35 p-5"><div className="absolute right-5 top-5 opacity-15"><TeamMark code={player.teamCode} className="h-28 w-28" /></div><div className="relative flex items-start gap-4"><PlayerPortrait key={player.headshotPath || player.playerRef} player={player} className="h-28 w-24 sm:h-32 sm:w-28" /><div className="min-w-0 flex-1"><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-gold">Player profile</p><h2 className="mt-2 font-display text-3xl leading-none sm:text-4xl">{player.name}</h2><p className="mt-3 text-xs text-muted-foreground">{player.teamCode} · {player.positions.join('/')} · {player.seasonStartYear}–{String(player.seasonStartYear+1).slice(-2)}</p><span className={player.available ? 'mt-3 inline-block rounded-full border border-positive/30 bg-positive/5 px-2 py-1 text-[10px] text-positive' : 'mt-3 inline-block rounded-full border border-border/30 px-2 py-1 text-[10px] text-muted-foreground'}>{player.available ? 'Observed source' : 'Stats unavailable'}</span></div>{onRemove && <button type="button" onClick={() => onRemove(player)} aria-label={`Remove ${player.name}`} className="relative shrink-0 rounded-lg border border-border/30 p-2 text-muted-foreground hover:text-foreground"><X className="h-4 w-4" /></button>}</div></header><div className="p-5"><nav aria-label={`${player.name} detail tabs`} className="flex gap-1 rounded-lg bg-canvas/40 p-1">{['profile','stats','bio'].map(key => <button type="button" key={key} onClick={() => setTab(key)} aria-pressed={tab === key} className={tab === key ? 'min-h-10 flex-1 rounded-md bg-gold/10 text-xs font-semibold capitalize text-gold' : 'min-h-10 flex-1 rounded-md text-xs capitalize text-muted-foreground hover:bg-raised'}>{key}</button>)}</nav>{tab === 'profile' && <><BlueprintStatGrid player={player} /><TrophyCase context={context} status={status} /></>}{tab === 'stats' && <BlueprintStatsTable player={player} />}{tab === 'bio' && <PlayerBio player={player} context={context} status={status} />}<p className="mt-4 text-[10px] leading-relaxed text-muted-foreground">{player.statsSource}. Player portraits and biography context may be current; statistics remain bound to the selected team, season and phase.</p></div></article>;
}