import React, { useState } from 'react';
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { statText } from '@/components/players/blueprintModel';
const METRICS=[['pts','Points / game'],['ast','Assists / game'],['reb','Rebounds / game'],['mpg','Minutes / game']];
const COLORS=['hsl(var(--primary))','hsl(var(--chart-2))','hsl(var(--chart-3))','hsl(var(--chart-4))'];
export default function BlueprintMetricChart({ players }) {
  const [metric,setMetric]=useState('pts');
  const rows=players.filter(player=>Number.isFinite(player.stats[metric])).map(player=>({name:`${player.name} · ${player.teamCode}`,value:player.stats[metric],games:player.stats.gp}));
  return <div className="mb-6 rounded-xl border border-border/30 bg-canvas/35 p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-display text-xl tracking-wide">THE COMPARISON DESK</h3><p className="mt-1 text-[11px] text-muted-foreground">Observed rates · no composite rating</p></div><label className="text-xs text-muted-foreground">Compare metric<select className="studio-select mt-1 sm:w-48" value={metric} onChange={event=>setMetric(event.target.value)}>{METRICS.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>{rows.length?<div className="h-60" role="img" aria-label={`Selected players compared by ${METRICS.find(([key])=>key===metric)[1]}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} layout="vertical" margin={{top:4,right:25,bottom:4,left:4}}><CartesianGrid horizontal={false} stroke="hsl(var(--border) / .2)"/><XAxis type="number" tick={{fill:'hsl(var(--muted-foreground))',fontSize:11}} axisLine={false} tickLine={false}/><YAxis type="category" dataKey="name" width={125} tick={{fill:'hsl(var(--foreground))',fontSize:10}} axisLine={false} tickLine={false}/><Tooltip cursor={{fill:'hsl(var(--secondary) / .4)'}} contentStyle={{background:'hsl(var(--card))',color:'hsl(var(--foreground))',border:'1px solid hsl(var(--border) / .4)',borderRadius:10}} formatter={value=>[statText(metric,value),METRICS.find(([key])=>key===metric)[1]]}/><Bar dataKey="value" radius={[0,5,5,0]} maxBarSize={28} isAnimationActive={false}>{rows.map((row,index)=><Cell key={row.name} fill={COLORS[index]}/>)}</Bar></BarChart></ResponsiveContainer></div>:<p className="py-6 text-sm text-muted-foreground">This metric is not supplied for the selected records.</p>}{rows.length!==players.length&&<p className="mt-2 text-xs text-muted-foreground">Players without a supplied value are omitted from the chart, not treated as zero.</p>}</div>;
}