import React, { useState } from 'react';
import { perGameStats, per36Stats } from '@/lib/season/labs';
const FIELDS = [['pts','points','PTS'],['reb','rebounds','REB'],['ast','assists','AST'],['stl','steals','STL'],['blk','blocks','BLK'],['tov','turnovers','TOV']];
export default function PlayerProfileViews({ player, year, source }) {
  const [tab, setTab] = useState('Profile');
  const [unit, setUnit] = useState('game');
  const stats = perGameStats(player);
  const rates = per36Stats(player);
  return <section className="court-panel p-5"><nav aria-label="Player detail sections" className="flex flex-wrap gap-1 border-b border-border pb-3">{['Profile','Stats','Bio'].map(value => <button type="button" key={value} aria-pressed={tab === value} onClick={() => setTab(value)} className={tab === value ? 'rounded-lg bg-gold/10 px-4 py-2 text-sm font-medium text-gold' : 'rounded-lg px-4 py-2 text-sm text-muted-foreground hover:bg-raised'}>{value}</button>)}</nav>
    {tab === 'Profile' && <><p className="mt-4 text-[10px] uppercase tracking-widest text-muted-foreground">Observed · {year}–{year + 1} · Regular season</p><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['GP',player.games],['PTS/G',stats.pts],['REB/G',stats.reb],['AST/G',stats.ast]].map(([label,value]) => <div key={label} className="rounded-lg bg-raised/60 p-3"><p className="text-[10px] text-muted-foreground">{label}</p><p className="font-display text-3xl text-foreground">{Number(value).toFixed(label === 'GP' ? 0 : 1)}</p></div>)}</div><p className="mt-4 text-xs text-muted-foreground">{player.minutes.toLocaleString()} source minutes across {player.games} reported games. Aggregated player stints may include more than one team.</p></>}
    {tab === 'Stats' && <><label className="mt-4 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">Units<select value={unit} onChange={event => setUnit(event.target.value)} className="rounded-md border border-input bg-raised px-3 py-2 text-foreground"><option value="game">Per game</option><option value="total">Season totals</option><option value="36">Per 36 minutes</option></select></label><div className="mt-3 overflow-x-auto" tabIndex={0} aria-label="Observed player statistics"><table className="w-full text-sm"><caption className="mb-3 text-left text-xs text-muted-foreground">Regular season · {player.games} reported games · {unit === 'game' ? 'per-game rates' : unit === 'total' ? 'totals' : 'per 36 minutes'}</caption><thead><tr>{FIELDS.map(([, , label]) => <th key={label} className="text-right">{label}</th>)}</tr></thead><tbody><tr>{FIELDS.map(([rate,total,label]) => <td key={label} className="text-right font-mono">{Number(unit === 'total' ? player[total] : unit === '36' ? rates[rate] : stats[rate]).toFixed(unit === 'total' ? 0 : 1)}</td>)}</tr></tbody></table></div></>}
    {tab === 'Bio' && <dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2">{[['Player identity',player.name],['Source player ref',player.playerRef],['Listed team',player.teamCode],['Source positions',player.positions?.join(' / ') || 'Not supplied'],['Biography / birth date','Not supplied by this season source'],['Evidence',source?.entry?.packageId || 'Season package']].map(([label,value]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 break-words text-foreground">{value}</dd></div>)}</dl>}
  </section>;
}