// Official NBA.com sources inspected on 2026-10-07. Links remain on NBA.com;
// article clips are identified as film-study loops, not standalone videos.
export const NBA_FILM = {
  pnr: { url: 'https://www.nba.com/watch/video/film-study-chris-paul-in-pick-and-roll', label: 'Chris Paul & OKC: pick-and-roll', format: 'Game-film video', detail: 'NBA Film Study: Paul and the Thunder execute pick-and-roll possessions.' },
  horns: { url: 'https://www.nba.com/nuggets/videos/mpj-for-three-out-of-horns', label: 'Denver: MPJ scores out of HORNS', format: 'Game video · 0:12', detail: 'Official Nuggets game highlight explicitly identified as a HORNS set.' },
  backdoor: { url: 'https://www.nba.com/nets/videos/durant-backdoor-play', label: 'Kevin Durant: backdoor vs. Portland', format: 'Game video · 0:09', detail: 'Nets vs. Trail Blazers, November 17, 2022: Durant backdoor play.' },
  inbound: { url: 'https://www.nba.com/watch/video/best-out-of-bounds-plays-of-the-2025-26-nba-season', label: 'NBA: out-of-bounds game plays', format: 'Game-video compilation', detail: 'Official NBA compilation of executed inbound plays from the 2025–26 season.' },
  nuggets: { url: 'https://www.nba.com/nuggets/videos/this-offense-is-elite-denver-nuggets-film-study', label: 'Denver: offense vs. Phoenix', format: 'Game-film video · 6:42', detail: 'Nuggets Knowledge breaks down Denver’s offense against the Suns; related concepts, not a verified copy of this set.' },
  spain: { url: 'https://www.nba.com/news/film-study-key-plays-actions-2022-playoffs', label: 'Phoenix: Spain pick-and-roll vs. Utah', format: 'Film study with game clips', detail: 'Section 1, “The Suns go to Spain”: Paul, Ayton and Booker, April 8, 2022. Also shows Booker popping for 3.' },
  drag: { url: 'https://www.nba.com/news/film-study-key-plays-actions-2022-playoffs', label: 'Milwaukee: staggered ball screens', format: 'Film study with game clips', detail: 'Section 2: Middleton and Antetokounmpo screen for Holiday against Philadelphia, March 29, 2022.' },
  offball: { url: 'https://www.nba.com/news/film-study-key-plays-actions-2022-playoffs', label: 'Miami: back-screen into curl screens', format: 'Film study with game clips', detail: 'Section 3: Robinson screens for Adebayo, then curls off screens; related off-ball screening sequences.' },
  zoom: { url: 'https://www.nba.com/news/film-study-key-plays-actions-2022-playoffs', label: 'Dallas: screen into Dončić handoff', format: 'Film study with game clips', detail: 'Section 4: Brunson screens for Dončić before Powell’s handoff, vs. Detroit, April 6, 2022.' },
  dho: { url: 'https://www.nba.com/news/film-study-key-plays-actions-2023-playoffs', label: 'Sacramento: Sabonis–Huerter handoff', format: 'Film study with game clips', detail: 'Section 1: real Kings handoffs, with shots, rolls and a switch counter.' },
  inverted: { url: 'https://www.nba.com/news/film-study-key-plays-actions-2023-playoffs', label: 'Boston: Tatum screens for a guard', format: 'Film study with game clips', detail: 'Section 2: Tatum as screener against Sacramento, March 21, 2023.' },
  post: { url: 'https://www.nba.com/news/film-study-key-plays-actions-2023-playoffs', label: 'Clippers: Leonard cross-screen post entry', format: 'Film study with game clips', detail: 'Section 3: cross-screen into a Leonard post-up, with the left side cleared.' },
  empty: { url: 'https://www.nba.com/news/film-study-key-plays-actions-2023-playoffs', label: 'Knicks: Brunson with an empty corner', format: 'Film study with game clips', detail: 'Section 4: empty-corner pick-and-rolls, including a pistol screen into a big-man screen.' },
  zone: { url: 'https://www.nba.com/news/film-study-how-lakers-can-attack-heat-zone', label: 'Lakers/Celtics vs. Miami’s 2–3 zone', format: 'Film study with game clips', detail: 'Inside/outside ball screens, Davis high-post/high-low passes and post-and-cut possessions against Miami’s zone.' },
  switch: { url: 'https://www.nba.com/news/finals-film-study-game-5', label: '2022 Finals: switches & switch counters', format: 'Film study with game clips', detail: 'Warriors–Celtics Game 5: mismatches, pre-switches, switch-backs and help at the rim.' },
  drop: { url: 'https://www.nba.com/news/film-study-anthony-davis-lakers-stretch-run', label: 'Anthony Davis: rolls and rim protection', format: 'Film study with game clips', detail: 'Lakers vs. Pelicans, March 14, 2023; offensive rolls and defensive drop coverage.' },
  transition: { url: 'https://www.nba.com/news/finals-film-study-thunder-pacers-game-5', label: '2025 Finals: Thunder transition & press break', format: 'Film study with game clips', detail: 'Thunder–Pacers Game 5: cuts, transition finishes and high screens against backcourt pressure.' },
};