import { sequence as q, move as m, defend as d, together as t, pass as p, screen as s, cutOffScreen as u, hold as h, note as n, mark, branch, shot, SPREAD, FIVE, BOX, ZOOM, PISTOL, TRANSITION } from '@/components/playbook/playSequence';

const transition = steps => q(TRANSITION, steps, { courtHeight: 940 });
/** @param {Record<string, string | number[]>} setup */
const zone = (steps, setup = SPREAD) => q(setup, steps, { zone: '2-3' });
/** @param {Record<string, string | number[]>} setup */
const blob = (steps, setup = BOX) => q({ ...setup, O1: [300, -25] }, steps, { inbounder: 'O1', inboundSide: 'baseline' });
/** @param {Record<string, string | number[]>} setup */
const slob = (steps, setup = SPREAD, inbounder = 'O1') => q({ ...setup, [inbounder]: [525, 275] }, steps, { owner: inbounder, inbounder, inboundSide: 'sideline' });

export default {
  'Primary Fast Break': q(TRANSITION, [[h('O5 secures the rebound at the defensive end.')], [m({ O1: [180, 750] }), p('O1')], [m({ O1: 'top', O2: [425, 280], O3: [75, 290] })], [m({ O5: 'rim', O4: 'left-slot' })], [h('O1 has advanced through the middle with the wide lanes filled.')], [p('O5'), n('Example: the rim runner arrives before X5.')]], { owner: 'O5', courtHeight: 940 }),
  'Hit-Ahead Break': q(TRANSITION, [[p('O1')], [m({ O1: [250, 450], O2: [425, 200], O3: [75, 210] })], [p('O2')], [m({ O2: [290, 95] })], [m({ O5: 'top', O4: 'left-slot' })]], { owner: 'O5', courtHeight: 940 }),
  'Rim Run': transition([[m({ O1: 'top', O2: 'right-wing', O3: 'left-wing', O4: 'left-slot', O5: [250, 200] })], [t(m({ O5: 'rim' }), d({ X5: [300, 160] }))], [h('O5 holds the inside seal.')], [mark('rim'), p('O5'), n('Example: the advancing guard finds the early rim feed.')], [branch('rim', 'Alternate read: the feed is covered; O5 exits to the dunker spot.'), m({ O5: 'right-dunker' })]]),
  'Drag Screen': transition([[m({ O1: 'top', O2: 'right-corner', O3: 'left-corner', O4: 'left-wing' })], [s('O5', 'X1')], [u('O1', [360, 235], 'O5')], [m({ O1: [305, 150], O5: 'rim' })], [h('The wide lanes are already filled as O5 rolls.')], [p('O5'), n('Example: select the roll pass.')]]),
  'Double Drag Roll-Pop': q({ ...FIVE, O1: [250, 390], O4: [170, 350], O5: [330, 350] }, [[s('O4', 'X1', 'ball', [190, 290])], [s('O5', 'X1', 'ball', [310, 240])], [u('O1', [250, 270], 'O4'), u('O1', [385, 245], 'O5')], [m({ O1: [385, 180], O4: 'left-slot', O5: 'rim' })], [h('C holds the rim target while PF stays available on the pop.')], [p('O4'), n('Example: the defender follows the roll; choose the pop.')]]),
  'Early Pistol': q(PISTOL, [[m({ O1: 'right-wing' })], [m({ O2: [445, 265] })], [s('O5', 'X2')], [p('O2', true), u('O2', [305, 150], 'O5')], [m({ O1: 'right-corner' })], [h('O3/O4 hold weak-side spacing.')]]),
  'Flow Into Delay': q({ ...FIVE, O1: [250, 420], O5: [330, 380] }, [[m({ O1: 'right-slot', O5: 'top' })], [p('O5'), n('Example: no fast-break shot appears.')], [m({ O4: 'left-wing', O2: 'right-corner', O3: 'left-corner' })], [m({ O1: [290, 285] }), p('O1', true), m({ O1: [310, 165] })], [m({ O1: 'right-wing', O5: 'top' }), p('O5')]]),
  'Zone Overload': zone([[p('O2')], [m({ O4: 'right-corner' })], [m({ O5: 'right-short_corner' })], [m({ O1: 'right-slot' })], [d({ X2: [380, 205], X4: [360, 105] }), n('Two right-side defenders must cover three receiving windows.')], [p('O5'), n('Example: the short corner is uncovered.')]], { ...SPREAD, O5: 'left-block' }),
  'High-Post Flash': zone([[p('O2')], [m({ O4: 'high_post' })], [p('O4')], [h('O4 catches facing the basket.')], [p('O5'), n('Example: choose the high-low pass.')]]),
  'Short-Corner Flash': zone([[p('O2')], [m({ O5: 'right-short_corner' })], [p('O5')], [d({ X5: [330, 85] })], [p('O4'), n('Example: draw the center, then find the high post.')]], { ...SPREAD, O4: 'high_post' }),
  'Baseline Runner': zone([[h('O5 starts in the right short corner.')], [p('O3'), m({ O5: [250, 40] })], [m({ O5: 'left-short_corner' })], [p('O5')], [p('O1'), p('O2'), m({ O5: 'right-short_corner' })]], { ...SPREAD, O5: 'right-short_corner' }),
  'Overload → Skip': zone([[m({ O2: 'right-corner', O4: 'right-elbow', O5: 'right-short_corner' })], [m({ O1: 'right-wing' })], [h('O3 holds the left wing.')], [p('O3')], [shot(), n('Example: O3 takes the open skip-pass shot.')], [m({ O4: 'right-block' })]]),
  'Ball Screen vs Zone': zone([[s('O5', 'X2')], [u('O1', [315, 200], 'O5')], [m({ O5: 'nail' })], [d({ X5: [250, 145] })], [p('O2'), n('Example: the middle rotation leaves the right corner open.')]], { ...FIVE, O2: 'right-corner', O5: 'right-elbow' }),
  'Pin-In vs Zone': zone([[p('O2')], [m({ O5: [335, 110] })], [s('O5', 'X4', 'pin', [335, 110])], [h('O4 holds the right corner beyond the pinned low defender.')], [p('O4')]], { ...SPREAD, O4: 'right-corner', O5: 'left-block' }),
  'High-Low vs Zone': zone([[p('O4')], [m({ O5: 'rim' })], [mark('high-low'), h('O4 faces the low target.')], [d({ X5: [250, 165] }), p('O5'), n('Example: X5 steps up, opening the low feed.')], [branch('high-low', 'Alternate read: the baseline defender pinches O5.'), d({ X4: [300, 110] }), p('O2')]], { ...SPREAD, O4: 'high_post', O2: 'right-corner' }),
  'Skip-and-Drive': { ...zone([[p('O3')], [h('O3 catches while the zone shifts left.')], [m({ O3: [170, 135] })], [m({ O4: [295, 180], O5: 'right-dunker' })], [p('O5'), n('Example: the drive creates a dump-off.')]], { ...SPREAD, O4: 'high_post' }), owner: 'O2' },
  'Box BLOB – Cross Screen Post': blob([[s('O4', 'X5', 'cross')], [u('O5', 'right-block', 'O4')], [m({ O2: 'right-slot' })], [h('O1 checks the post; X5 covers the entry.')], [s('O3', 'X4', 'down'), u('O4', 'left-wing', 'O3'), p('O4'), n('Example: use the screen-the-screener outlet.')]], { ...BOX, O4: 'right-block', O5: 'left-block', O2: 'right-elbow' }),
  'Box BLOB – Screen the Screener': blob([[s('O4', 'X2', 'down'), t(u('O2', 'right-corner', 'O4', false), d({ X2: [405, 125] }))], [d({ X4: [375, 150] }), s('O5', 'X4', 'back')], [u('O4', 'rim', 'O5')], [p('O4'), n('Example: the second cutter is open.')], [m({ O3: 'left-wing' })]]),
  'Box BLOB – Elevator': blob([[h('O2 starts low in the box.')], [m({ O4: [175, 220], O5: [325, 220] })], [m({ O2: [250, 335] }, { O2: [[250, 220]] })], [t(m({ O4: [228, 220], O5: [272, 220] }), d({ X2: [250, 165] }))], [p('O2'), shot()], [m({ O3: 'left-corner' })]]),
  'Stack BLOB – Slip': blob([[m({ O2: [340, 190], O3: [150, 195], O4: [300, 150], O5: [200, 150] })], [m({ O4: [370, 200] })], [m({ O4: 'rim' })], [m({ O2: 'right-wing', O3: 'left-wing' })], [p('O4'), n('Example: the slip is open before the switch.')]], { O2: [250, 100], O3: [250, 170], O4: [250, 240], O5: [250, 310] }),
  'BLOB Lob': blob([[h('O5 begins at the left elbow, away from the rim.')], [s('O4', 'X5', 'back')], [u('O5', 'rim', 'O4')], [p('O5')], [m({ O2: 'right-corner', O3: 'left-corner' })]], { ...BOX, O5: 'left-elbow', O4: 'left-block', O3: 'right-elbow' }),
  'BLOB Hammer': blob([[p('O2')], [m({ O2: [380, 70] })], [s('O4', 'X3', 'flare')], [u('O3', 'left-corner', 'O4')], [p('O3')], [m({ O1: 'right-slot' })]], { ...SPREAD, O4: 'left-block' }),
  'SLOB → Pick-and-Roll': slob([[p('O2')], [m({ O1: 'right-corner' })], [s('O5', 'X2')], [u('O2', [295, 150], 'O5')], [m({ O5: 'rim' })], [m({ O3: 'left-wing', O4: 'left-corner' })]]),
  'SLOB Spain': slob([[p('O1')], [s('O5', 'X1')], [m({ O2: [310, 130] })], [u('O1', [315, 160], 'O5'), m({ O5: [220, 150] })], [s('O2', 'X5', 'back'), m({ O5: 'rim' }), m({ O2: 'right-slot' })], [m({ O3: 'left-corner', O4: 'left-wing' })]], SPREAD, 'O3'),
  'SLOB Zoom': slob([[p('O5')], [s('O4', 'X2', 'down')], [u('O2', 'right-wing', 'O4')], [m({ O5: [350, 265], O2: [400, 265] }), p('O2', true)], [m({ O2: [280, 145] })], [m({ O1: 'left-slot' })]], ZOOM),
  'SLOB Isolation': slob([[p('O1')], [t(m({ O5: 'left-block' }), m({ O4: 'left-slot' }), m({ O2: 'left-corner', O3: 'left-wing' }))], [h('O1 waits for all four teammates to clear left.')], [m({ O1: [355, 130] })], [h('Weak-side teammates remain available for help-driven kick-outs.')]], { ...SPREAD, O1: 'right-wing' }, 'O2'),
};
