import { sequence as q, move as m, defend as d, together as t, pass as p, screen as s, cutOffScreen as u, hold as h, note as n, mark, branch, swap, SPREAD, FIVE, HORNS, BOX, DIAMOND } from '@/components/playbook/playSequence';

const POST = { ...SPREAD, O1: 'right-slot', O5: 'right-block', O4: 'left-elbow' };
const ELBOW = { ...FIVE, O5: 'right-elbow', O1: 'top', O2: 'right-wing' };

export default {
  'Horns Twist': q(HORNS, [[m({ O1: [290, 280] })], [s('O5', 'X1')], [u('O1', [385, 210], 'O5')], [m({ O4: [325, 170] })], [s('O4', 'X1', 'ball', [325, 170]), u('O1', [220, 140], 'O4')], [m({ O5: 'right-dunker', O4: 'left-slot' })], [h('O2/O3 hold the corners.')]]),
  'Horns Flare': q(HORNS, [[p('O5'), m({ O3: 'left-slot' })], [s('O4', 'X3', 'flare')], [u('O3', 'left-corner', 'O4'), mark('flare')], [p('O3'), n('Example: O3 lifts, then flares away from the elbow hub to the corner.')], [branch('flare', 'Alternate read: the flare is denied; return the ball to O1 by handoff.'), m({ O1: [280, 190] }), p('O1', true)], [m({ O4: 'rim' })]]),
  'Horns Dive': q(HORNS, [[m({ O1: [290, 275] })], [m({ O4: 'left-dunker' })], [s('O5', 'X1')], [u('O1', [310, 145], 'O5')], [h('O4 occupies the low helper from the left dunker spot.')], [p('O4'), n('Example: select the opposite-horn dump-off.')]]),
  'Horns Spain': q(HORNS, [[h('Hold the Horns shell.')], [s('O5', 'X1')], [m({ O4: [255, 160] })], [u('O1', [315, 160], 'O5')], [m({ O5: [220, 150] })], [s('O4', 'X5', 'back'), m({ O5: 'rim' }), m({ O4: 'left-slot' })], [h('O2/O3 keep corner spacing.')]]),
  'Horns Zoom': q(HORNS, [[p('O5'), m({ O1: 'left-slot' })], [s('O4', 'X2', 'down')], [u('O2', [375, 210], 'O4')], [p('O2', true)], [m({ O2: [275, 145] })], [m({ O4: 'right-slot', O5: 'rim' })]]),
  'Horns UCLA': q({ ...HORNS, O2: 'right-wing' }, [[p('O2')], [s('O5', 'X1', 'back')], [u('O1', 'rim', 'O5')], [h('O2 checks the rim; X5 stays in help.')], [m({ O1: 'left-corner', O3: 'left-slot' }), p('O5'), n('Example: the initial pass is covered.')], [s('O4', 'X3', 'flare'), u('O3', 'left-wing', 'O4')]]),
  'Horns High-Low': q(HORNS, [[p('O4')], [m({ O5: 'right-block' })], [mark('high-low'), h('O4 faces the low-post target.')], [d({ X5: [290, 150] }), p('O5'), n('Example: lob over X5’s front.')], [branch('high-low', 'Alternate read: interior help collapses; kick to the corner.'), d({ X2: [365, 125] }), p('O2')], [m({ O1: 'right-slot' })]]),
  'Box Zipper': q(BOX, [[h('O2 begins at the right block.')], [s('O5', 'X2', 'down')], [t(m({ O1: 'left-slot' }), u('O2', 'top', 'O5'))], [p('O2')], [m({ O3: 'left-corner', O4: 'right-corner' })], [s('O5', 'X2'), u('O2', [310, 150], 'O5')]]),
  'Box Elevator': q(BOX, [[h('O2 holds the low spot.')], [m({ O4: [175, 215], O5: [325, 215], O1: 'left-slot' })], [m({ O2: [250, 335] }, { O2: [[250, 215]] })], [m({ O4: [228, 215], O5: [272, 215] })], [p('O2')], [m({ O3: 'left-corner' })]]),
  'Diamond Pindown': q(DIAMOND, [[h('O2 starts at the low point.')], [m({ O4: 'right-elbow', O5: 'left-elbow', O3: 'left-slot' })], [m({ O1: 'top', O3: 'left-slot' })], [s('O4', 'X2', 'down'), u('O2', 'right-wing', 'O4'), n('Example: choose the right-side exit.')], [p('O2')], [m({ O5: 'left-corner' })]]),
  'Diamond Backdoor': q(DIAMOND, [[h('Hold the same diamond shell.')], [t(s('O4', 'X2', 'down'), m({ O2: [360, 150] }))], [d({ X2: [365, 210] }), m({ O2: 'rim' }), n('X2 top-locks; O2 goes backdoor.')], [p('O2')], [m({ O4: 'right-block', O5: 'left-block' })]]),
  'Stack Slip': q({ ...SPREAD, O2: [330, 210], O4: [330, 150] }, [[h('O2/O4 hold a compact two-player stack.')], [m({ O4: [365, 215] })], [d({ X2: [390, 170], X4: [320, 250] }), m({ O4: 'rim' })], [m({ O2: 'right-slot' })], [p('O4'), n('Example: choose the slip instead of the outside receiver.')]]),
  'Post Split': q(POST, [[p('O5')], [s('O1', 'X2', 'back')], [u('O2', 'rim', 'O1')], [h('O5 reads O2 at the rim and O1 outside.')], [m({ O2: 'right-corner', O5: [280, 105] }), n('Example: the split is covered; O5 attacks the post.')], [h('O3/O4 maintain weak-side spacing.')]]),
  'Elbow Split': q(ELBOW, [[p('O5')], [m({ O1: [275, 280], O2: [365, 270] })], [s('O1', 'X2', 'back'), u('O2', 'rim', 'O1')], [h('O5 faces the rim cutter; the passing window is covered.')], [m({ O2: 'right-corner', O1: [300, 225] }), p('O1', true)]]),
  'Elbow Backdoor': q(ELBOW, [[p('O5')], [m({ O2: [405, 230] })], [d({ X2: [390, 285] })], [m({ O2: 'rim' })], [p('O2')], [m({ O1: 'left-slot', O3: 'left-wing', O4: 'right-slot' })]]),
  'Top Isolation': q(FIVE, [[m({ O2: 'right-corner', O3: 'left-corner', O4: 'left-short_corner', O5: 'right-dunker' })], [h('O4/O5 hold the flattened baseline spots as the corners fill.')], [h('O1 waits above the arc until spacing is set.')], [m({ O1: [305, 130] })], [d({ X3: [185, 120] }), m({ O3: 'left-wing' }), n('Example: X3 commits to help and O3 lifts behind him.')]]),
  'Empty-Side Isolation': q(SPREAD, [[m({ O1: 'right-wing', O2: 'left-slot', O3: 'left-wing', O4: 'left-corner', O5: 'left-block' })], [h('All four teammates clear left while O1 arrives on the right wing.')], [h('O1 waits until the right side is clear.')], [m({ O1: [375, 100] })], [h('Weak-side players hold ready for a skip pass.')]]),
  'Switch Hunt Isolation': q(SPREAD, [[h('O1 targets X5 for the switch.')], [s('O5', 'X1')], [u('O1', [330, 235], 'O5'), swap('X1', 'X5')], [m({ O5: 'left-block' })], [m({ O2: 'right-corner', O3: 'left-wing', O4: 'left-corner' })], [m({ O1: [350, 115] }), n('O1 now attacks X5 after the confirmed switch.')]]),
  'Punch / Direct Post Entry': q(POST, [[h('O5 seals on the right block.')], [m({ O1: 'right-wing', O2: 'right-corner' })], [p('O5')], [m({ O2: 'right-corner', O1: 'right-slot' })], [m({ O5: [300, 105] })], [d({ X2: [350, 115] }), p('O2'), n('Example: X2 doubles the post; O5 kicks to O2.')]]),
  'Cross-Screen Post-Up': q({ ...POST, O4: 'right-block', O5: 'left-block' }, [[s('O4', 'X5', 'cross')], [u('O5', 'right-block', 'O4')], [h('O5 seals X5 behind the ball-side shoulder.')], [p('O5')], [m({ O4: 'left-short_corner' })]]),
  'Wedge Post-Up': q({ ...POST, O5: 'left-elbow', O4: 'right-block' }, [[s('O4', 'X5', 'cross')], [u('O5', 'right-block', 'O4')], [h('O5 holds the seal after X5 is displaced.')], [p('O5')], [m({ O4: 'left-corner' })]]),
  'High-Low Entry': q({ ...POST, O4: 'left-elbow' }, [[p('O4')], [d({ X5: [280, 145] }), h('O5 seals the fronting X5.')], [mark('high-low'), h('O4 faces the rim.')], [p('O5'), n('Example: pass over X5’s front.')], [d({ X3: [185, 110] }), m({ O3: 'left-slot' })], [branch('high-low', 'Alternate read: the high-low pass is covered.'), m({ O4: [220, 140] })]]),
  'Post DHO': q(ELBOW, [[p('O5')], [m({ O2: [375, 220] })], [h('O5 protects the ball on the outside hip.')], [p('O2', true)], [s('O5', 'X2', 'handoff'), m({ O5: 'right-block' })], [m({ O2: [270, 130] })]]),
  'Post → Hammer': q({ ...POST, O4: 'left-block' }, [[p('O5')], [m({ O5: [365, 70] })], [s('O4', 'X3', 'flare')], [u('O3', 'left-corner', 'O4')], [p('O3')], [h('The post driver stays below the help, preserving the corner window.')]]),
};
