// Generated by scripts/sync-forge-athlete.mjs from the reviewed model UV atlas.
function panel(ctx,image,box,offset,rear){
  if(!image||!box)return;
  const [x,y,w,h]=box;
  // Keep artwork clear of the armholes. The source's interior neck label
  // and photo background are deliberately outside the sampled panel.
  const top=rear?.12:.20;
  const height=rear?862:792;
  const fabric=document.createElement('canvas');fabric.width=328;fabric.height=height;
  const surface=fabric.getContext('2d');surface.imageSmoothingQuality='high';
  surface.drawImage(image,x+w*.12,y+h*top,w*.76,h*(.94-top),0,0,328,height);
  const pixels=surface.getImageData(0,0,328,height);
  const smooth=value=>{const t=Math.max(0,Math.min(1,value));return t*t*(3-2*t);};
  // Flat photographs contain background inside their armhole corners. Curve
  // the upper panel inward and blend its perimeter into the base fabric, so
  // that no rectangular photo edge appears on the raised-arm garment.
  for(let row=0;row<height;row++){
    const inset=44*(1-smooth((row-35)/250));
    for(let col=0;col<328;col++){
      const fade=smooth((col-inset)/18)*smooth((327-inset-col)/18)*smooth(row/10)*smooth((height-1-row)/14);
      pixels.data[(row*328+col)*4+3]=Math.round(255*fade);
    }
  }
  surface.putImageData(pixels,0,0);
  ctx.drawImage(fabric,offset+92,rear?100:170);
  // Map photographed side panels only below the armhole.
  for(const side of [0,1]){
    ctx.drawImage(image,x+w*(side?.87:.03),y+h*.43,w*.10,h*.51,offset+(side?474:0),430,38,532);
  }
}
function create(element,style,loaded){
  const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=1024;
  if(element==='jersey'){canvas.width=2048;canvas.height=2048;}
  if(element.includes('shoe')){canvas.width=1024;canvas.height=1024;}
  const ctx=canvas.getContext('2d');ctx.fillStyle=style.color;ctx.fillRect(0,0,canvas.width,canvas.height);
  if(element==='jersey'){ctx.scale(2,2);ctx.fillRect(0,0,1024,1024);ctx.imageSmoothingQuality='high';}
  if(element.includes('shoe')){
    const rgb=hex=>[1,3,5].map(at=>parseInt(hex.slice(at,at+2),16));
    const upper=rgb(style.color),sole=rgb(style.trimColor);
    const lerp=(x,xs,ys)=>{let at=0;while(at<xs.length-2&&x>xs[at+1])at++;const t=Math.max(0,Math.min(1,(x-xs[at])/(xs[at+1]-xs[at])));return ys[at]*(1-t)+ys[at+1]*t;};
    const pixels=ctx.createImageData(1024,1024);
    for(let row=0;row<1024;row++){
      const z=(row+.5)/1024*.326-.115;
      const top=lerp(z,[-.115,-.087,-.047,.065,.110,.200,.210],[.080,.121,.145,.113,.096,.079,.071]);
      for(let col=0;col<1024;col++){
        const theta=((col+.5)/1024-.5)*Math.PI*2,y=(top+.032)*.5+(top-.032)*.5*Math.cos(theta);
        const t=Math.max(0,Math.min(1,(y-.035)/.022)),blend=t*t*(3-2*t),at=(row*1024+col)*4;
        for(let c=0;c<3;c++)pixels.data[at+c]=Math.round(sole[c]*(1-blend)+upper[c]*blend);
        pixels.data[at+3]=255;
      }
    }
    ctx.putImageData(pixels,0,0);
    ctx.save();ctx.beginPath();ctx.rect(300,250,424,675);ctx.clip();
    // Dense woven upper and perforated toe ventilation use a subdued contrast.
    ctx.fillStyle='rgba(0,0,0,.24)';
    for(let y=265;y<940;y+=8)for(let x=305+(y%16?4:0);x<720;x+=8){ctx.beginPath();ctx.ellipse(x,y,1.2,1.8,0,0,Math.PI*2);ctx.fill();}
    ctx.restore();
    const lace=upper.map(value=>Math.round(value*.55+255*.45));
    ctx.strokeStyle=style.trimColor;ctx.lineWidth=10;ctx.lineJoin='round';
    // Reinforced eyestays and heel panels are symmetric on both shoes.
    for(const side of [-1,1]){
      const x=512+side*103;
      ctx.beginPath();ctx.moveTo(x+side*28,325);ctx.lineTo(x,750);ctx.lineTo(512+side*170,845);ctx.stroke();
      ctx.lineWidth=2;ctx.strokeStyle='rgba(255,255,255,.42)';ctx.setLineDash([3,5]);ctx.stroke();ctx.setLineDash([]);
      ctx.lineWidth=10;ctx.strokeStyle=style.trimColor;
      ctx.beginPath();ctx.moveTo(512+side*205,40);ctx.lineTo(512+side*170,175);ctx.lineTo(512+side*270,280);ctx.stroke();
    }
    ctx.strokeStyle='rgb('+lace.join(',')+')';ctx.lineWidth=6;ctx.lineCap='round';
    for(let i=0;i<6;i++){
      const y=510+i*43;ctx.beginPath();ctx.moveTo(422,y);ctx.lineTo(602,y+18);ctx.moveTo(602,y);ctx.lineTo(422,y+18);ctx.stroke();
      for(const x of [411,613]){ctx.fillStyle='rgba(0,0,0,.6)';ctx.beginPath();ctx.ellipse(x,y+9,5,7,0,0,Math.PI*2);ctx.fill();}
    }
    ctx.lineWidth=2;ctx.strokeStyle='rgba(255,255,255,.38)';ctx.setLineDash([4,6]);
    ctx.beginPath();ctx.ellipse(512,825,170,55,0,0,Math.PI);ctx.stroke();ctx.setLineDash([]);
  }else if(element==='basketball'){
    const width=1024,height=512;
    if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;}
    const shade=style.ballColor==='midnight'?'#182331':'#c86b2d', seam=style.ballColor==='midnight'?'#060a10':'#171717';
    ctx.fillStyle=shade;ctx.fillRect(0,0,width,height);
    // Fine, evenly spaced pebble dimples remain visible at the Forge viewer scale.
    ctx.fillStyle='rgba(42,18,8,.19)';
    for(let y=3;y<height;y+=7)for(let x=(y%14?0:3);x<width;x+=7){ctx.beginPath();ctx.ellipse(x,y,1.15,1.7,0,0,Math.PI*2);ctx.fill();}
    ctx.strokeStyle=seam;ctx.lineWidth=12;ctx.lineCap='round';
    ctx.beginPath();ctx.moveTo(0,256);ctx.lineTo(width,256);ctx.stroke();
    for(const center of [256,768]){
      ctx.beginPath();
      for(let x=0;x<=width;x+=4){const angle=x/width*Math.PI*2;const y=256+Math.sin(angle)*252; if(x===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}
      ctx.stroke();
    }
    ctx.strokeStyle='rgba(255,190,120,.28)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,238);ctx.lineTo(width,238);ctx.stroke();
  }else if(element==='jersey'){
    if(loaded?.front && loaded.layout?.front){panel(ctx,loaded.front,loaded.layout.front,0,false);}
    else{
      // The older three-quarter front is sampled as a bounded panel. This
      // is a fallback only when the archive has no usable flat photograph.
      if(loaded?.image)ctx.drawImage(loaded.image,1000,840,360,475,58,218,396,745);
      else {ctx.fillStyle=style.trimColor;ctx.fillRect(80,185,352,680);ctx.fillStyle=style.color;ctx.fillRect(110,210,292,625);ctx.fillStyle=style.accent||style.trimColor;ctx.fillRect(110,210,28,625);ctx.fillRect(374,210,28,625);}
    }
    if(loaded?.back && loaded.layout?.back)panel(ctx,loaded.back,loaded.layout.back,512,true);
    else if(loaded?.front && loaded.layout?.front){
      const [x,y,w,h]=loaded.layout.front;
      for(const side of [0,1])ctx.drawImage(loaded.front,x+w*(side?.87:.03),y+h*.43,w*.10,h*.51,512+(side?474:0),430,38,532);
    }
  }else if(element==='shorts'){
    // Original front quadrilateral, sampled row by row to avoid perspective
    // skew. Side seams use clean fabric colors instead of magnifying narrow
    // photographic strips, which included lighting and mannequin edge pixels.
    if(!loaded?.image){ctx.fillStyle=style.color;ctx.fillRect(0,32,1024,952);ctx.fillStyle=style.accent||style.trimColor;ctx.fillRect(472,32,80,952);}
    else for(let row=0;row<1024;row++){
      const t=(row+.5)/1024;
      ctx.drawImage(loaded.image,945-30*t,1343+661*t,443+64*t,1,0,row,512,1);
    }
    if(loaded?.image){const front=ctx.getImageData(0,0,512,1024).data;
    function fabric(row,start){
      const channels=[[],[],[]];
      for(let x=start;x<start+20;x++)for(let c=0;c<3;c++)channels[c].push(front[(row*512+x)*4+c]);
      return channels.map(values=>values.sort((a,b)=>a-b)[10]);
    }
    for(let row=0;row<1024;row++){
      const left=fabric(row,62),right=fabric(row,430);
      const color=left.map((value,c)=>Math.round((value+right[c])*.5));
      ctx.fillStyle='rgb('+color.join(',')+')';
      ctx.fillRect(512,row,512,1);
      // Front and rear share exact seam colors and uninterrupted horizontal
      // bands. Curved outer leg panels no longer smear the reference image.
      ctx.fillRect(0,row,40,1);ctx.fillRect(472,row,40,1);
    }
    }ctx.fillStyle=style.trimColor;ctx.fillRect(0,0,1024,32);ctx.fillRect(0,984,1024,15);
  }
  if(element==='jersey'||element==='shorts'){
    // A subtle woven finish follows the garment UVs and survives mipmapping.
    ctx.globalAlpha=.035;ctx.fillStyle='#ffffff';
    for(let at=0;at<1024;at+=4){ctx.fillRect(at,0,1,1024);ctx.fillRect(0,at,1024,1);}
    ctx.globalAlpha=1;
  }
  return canvas;
}

export default function forgeUniformAtlas(element, item, loaded) {
  return create(element, { color: element === "shorts" ? item?.shorts : item?.primary, trimColor: item?.accent || '#ffffff', accent: item?.accent || '#ffffff', ballColor: item?.ballColor }, loaded);
}
