// Generated by scripts/build-forge-evidence.mjs from reviewed local sources.
export const FORGE_EVIDENCE_RELEASE = [
  {
    "year": 2017,
    "packageVersion": "v4-canonical-20260929-fd23e18bcf46",
    "url": "/studio-assets/forge/ratings/2017-298db8cff085.json",
    "sha256": "298db8cff0853efeb27342eaa0f139b6aa0f61e2ed4dcdcb23cf41376036d943",
    "bytes": 256492
  },
  {
    "year": 2018,
    "packageVersion": "v4-canonical-20260929-721f9120944e",
    "url": "/studio-assets/forge/ratings/2018-dda8ab6a0112.json",
    "sha256": "dda8ab6a011225a1a28195dcc6e772532e3feeaaa2cecae0e5fb3879d77fba45",
    "bytes": 265280
  },
  {
    "year": 2019,
    "packageVersion": "v4-canonical-20260929-77c5c6f543a5",
    "url": "/studio-assets/forge/ratings/2019-ed60e3d2ebcd.json",
    "sha256": "ed60e3d2ebcd9a4bb85f1c65917e9ccf1b9b1f9f673bf441e83606943fd056cb",
    "bytes": 259024
  },
  {
    "year": 2020,
    "packageVersion": "v4-canonical-20260929-455fd1328d9b",
    "url": "/studio-assets/forge/ratings/2020-d5c6766ba7c8.json",
    "sha256": "d5c6766ba7c89b6d0a07b39be4afcbdfa40cae28b83f120ace1c03ee6f0fa8bb",
    "bytes": 281185
  },
  {
    "year": 2021,
    "packageVersion": "v4-canonical-20260929-147439a76a42",
    "url": "/studio-assets/forge/ratings/2021-c66cd4d0feb8.json",
    "sha256": "c66cd4d0feb854a9c8bdac962b82de6eb0256a7ec31dd494e0ecad9d0db42bfa",
    "bytes": 314920
  },
  {
    "year": 2022,
    "packageVersion": "v4-canonical-20260929-e7b8d23d62a6",
    "url": "/studio-assets/forge/ratings/2022-a137d7548903.json",
    "sha256": "a137d75489036f1965199b2f7111f71a6d2bec0b575145b77ec18209b9befadd",
    "bytes": 285461
  },
  {
    "year": 2023,
    "packageVersion": "v4-canonical-20260929-97b86518fdbc",
    "url": "/studio-assets/forge/ratings/2023-4ecc892a298b.json",
    "sha256": "4ecc892a298b0f6da835548d8ea3afb8b76ef3eaaad687adf3fbe73ca380125c",
    "bytes": 305130
  },
  {
    "year": 2024,
    "packageVersion": "v4-canonical-20260929-f9d068e584cd",
    "url": "/studio-assets/forge/ratings/2024-672ae5694ab7.json",
    "sha256": "672ae5694ab7933b6bcf48e198ff45acdd57d7033ed41a200d342824cd4346cd",
    "bytes": 298254
  },
  {
    "year": 2025,
    "packageVersion": "v4-canonical-20260929-1469d53a1c0c",
    "url": "/studio-assets/forge/ratings/2025-970b9f7affef.json",
    "sha256": "970b9f7affefb9f881a3e870c810b27a1b44ee75ee2821abb34e3c52baef7d1c",
    "bytes": 333413
  }
];
