// Generated by scripts/refine-forge-arms.py; matched to the elbow-corrected derivative.
export const FORGE_POSE_RELEASE = {
  "path": "pose-cycle-95215237078e.json",
  "bytes": 30588,
  "sha256": "95215237078e90aeb700eee00207b3ca141c1d7dd5419c25b0fb0f9c3931677a",
  "modelSha256": "a4afc942b31d81292600ba24c23d5da891e347b97868fd017c1a0b5b0726a1a1",
  "rotationsPerPose": 2,
  "poses": [
    "dunk",
    "jump-shot",
    "dribble"
  ]
};
