import React, { useState } from 'react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import MetricTile from '@/components/studio/MetricTile';
export default function RecordedCareerChart({ seasons }) {
  const [stat,setStat]=useState('pts'),[selectedYear,setSelectedYear]=useState(null);
  if(!seasons.length)return <section className="court-panel p-6"><h2 className="font-display text-2xl">NO RECORDED SEASONS</h2><p className="mt-3 text-sm text-muted-foreground">Select a player with observed regular-season history.</p></section>;
  const palette={pts:'hsl(var(--primary))',reb:'hsl(var(--chart-2))',ast:'hsl(var(--chart-3))'};
  const supplied=seasons.filter(row=>Number.isFinite(row[stat]));
  const peak=supplied.reduce((best,row)=>!best||row[stat]>best[stat]?row:best,null);
  const focus=seasons.find(row=>row.year===selectedYear)||seasons.at(-1);
  const byYear=new Map(seasons.map(row=>[row.year,row]));
  const chart=Array.from({length:seasons.at(-1).year-seasons[0].year+1},(_,index)=>{const year=seasons[0].year+index;return byYear.get(year)||{year,label:`${year}–${String(year+1).slice(-2)}`,pts:null,reb:null,ast:null};});
  const text=value=>Number.isFinite(value)?value.toFixed(1):'—';
  return <section className="court-panel p-5">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="court-kicker">Observed, not projected</p><h2 className="mt-1 font-display text-2xl">THE RECORDED CAREER PATH</h2></div><nav aria-label="Career chart statistic" className="flex gap-1 rounded-lg bg-canvas/40 p-1">{[['pts','Points'],['reb','Rebounds'],['ast','Assists']].map(([key,label])=><button key={key} type="button" aria-pressed={stat===key} onClick={()=>setStat(key)} className={stat===key?'min-h-10 rounded-md bg-gold/10 px-3 text-xs text-gold':'min-h-10 rounded-md px-3 text-xs text-muted-foreground hover:bg-raised'}>{label}</button>)}</nav></header>
    <div className="mt-5 h-72" role="img" aria-label={`Recorded ${stat} per game by season; missing archive seasons create gaps`}><ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{top:10,right:15,bottom:5,left:-15}} onClick={event=>{const row=event?.activePayload?.[0]?.payload;if(row&&byYear.has(row.year))setSelectedYear(row.year);}}><CartesianGrid vertical={false} stroke="hsl(var(--border) / .25)" strokeDasharray="3 3"/><XAxis dataKey="label" tick={{fill:'hsl(var(--muted-foreground))',fontSize:10}} tickLine={false} axisLine={false}/><YAxis tick={{fill:'hsl(var(--muted-foreground))',fontSize:11}} tickLine={false} axisLine={false}/><Tooltip contentStyle={{background:'hsl(var(--card))',color:'hsl(var(--foreground))',border:'1px solid hsl(var(--border) / .4)',borderRadius:10}} formatter={value=>[text(value),'Recorded / G']}/><Line type="linear" dataKey={stat} connectNulls={false} stroke={palette[stat]} strokeWidth={3} dot={{r:4,fill:palette[stat],stroke:'hsl(var(--card))',strokeWidth:2}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground">Click a recorded point or choose a season to inspect its exposure.</p><label className="text-xs text-muted-foreground">Inspect season<select className="studio-select mt-1 sm:w-40" value={focus.year} onChange={event=>setSelectedYear(Number(event.target.value))}>{seasons.map(row=><option key={row.year} value={row.year}>{row.label}</option>)}</select></label></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-3"><MetricTile label="Selected season / G" value={text(focus[stat])} detail={`${focus.label} · ${focus.teams.join(' / ')}`}/><MetricTile label="Recorded peak / G" value={text(peak?.[stat])} detail={peak?.label||'No supplied value'}/><MetricTile label="Selected season GP" value={focus.games} detail="Observed exposure, not projected games" tone="royal"/></div>
    <p className="mt-4 text-xs leading-relaxed text-muted-foreground">The chart shows only supplied regular-season observations inside 2017–26. Gaps are missing records—not zero production, retirement or a future aging scenario.</p>
  </section>;
}