import React, { useState } from 'react';
import { Search, X } from 'lucide-react';
import TeamMark from '@/components/studio/TeamMark';
export default function SpinExclusions({ players, excluded, onChange }) {
  const [query,setQuery] = useState('');
  const [limit,setLimit] = useState(40);
  const matches = players.filter(player => `${player.name} ${player.teamCode}`.toLowerCase().includes(query.toLowerCase()));
  const refs = new Set(excluded);
  const toggle = ref => onChange(refs.has(ref) ? excluded.filter(item => item !== ref) : [...excluded,ref].sort());
  return <section className="court-panel p-4"><div className="flex items-center justify-between gap-2"><h2 className="font-display text-2xl">POOL EXCLUSIONS</h2><span className="font-mono text-xs text-gold">{excluded.length}</span></div><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Excluded players cannot be drawn. Changing this list rebuilds the pool and clears previous picks.</p><label className="mt-4 flex items-center gap-2 rounded-lg border border-input bg-raised/40 px-3 py-2"><Search className="h-4 w-4 text-muted-foreground" /><input aria-label="Search players to exclude" className="min-w-0 w-full bg-transparent text-sm outline-none" value={query} onChange={event => { setQuery(event.target.value);setLimit(40); }} placeholder="Name or team…" /></label>{excluded.length > 0 && <button type="button" onClick={() => onChange([])} className="mt-3 flex min-h-9 items-center gap-1 text-xs text-gold"><X className="h-3 w-3" />Clear all exclusions</button>}<div className="mt-3 max-h-[28rem] space-y-1 overflow-y-auto">{matches.slice(0,limit).map(player => <label key={player.playerRef} className="flex min-h-12 cursor-pointer items-center gap-2 rounded-lg px-2 py-2 hover:bg-raised/50"><input type="checkbox" checked={refs.has(player.playerRef)} onChange={() => toggle(player.playerRef)} className="h-4 w-4 shrink-0 accent-gold" /><TeamMark code={player.teamCode} className="h-10 w-10" /><span className="min-w-0 flex-1 truncate text-xs">{player.name}</span></label>)}{!matches.length && <p className="py-4 text-xs text-muted-foreground">No players match your search.</p>}</div>{matches.length > limit && <button type="button" onClick={() => setLimit(value => value+40)} className="mt-3 min-h-10 w-full rounded-lg border border-input text-xs text-gold">Show more players</button>}</section>;
}